### PR TITLE
refactor: Fix Caching.

### PR DESCRIPTION
**Pull request by darkobits**
While going through the Contribute form on the website, I noticed that we weren't re-validating the `signal.art` URL if it changed (either from invalid to valid, or vice-versa). I traced the issue back to `stickers-client`, which was only caching based on pack ID. Because of this, when we called a `stickers-client` method with an _invalid_ key for a pack, then with a _valid_ key for a pack, we were receiving the same cached, rejected Promise from the first request/call. Conversely, when calling a method with a _valid_ key followed by an _invalid_ key, we would get the cached, resolved Promise from the first request/call. This update creates cache keys based on all incoming parameters that would reasonably cause the expected return value to change.

Additionally:

* Browser-based crypto methods now check for the presence of the SubtleCrypto API before trying to use it.
* Added unit tests.
* Updated dependencies.

### CODE REVIEW

**Comment by darkobits** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ src/lib/stickers-client.ts  79
+ src/index.ts  50
+ src/browser.ts  100
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signalstickers/stickers-client/pullRequest?prid=5352602&bid=17533938)

**Comment by darkobits** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ src/lib/stickers-client.ts  79
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signalstickers/stickers-client/pullRequest?prid=5352602&bid=17533938)

**Comment by romainricard** [comment]
I can't reproduce the initial bug, but LGTM! :star2:

**Review by romainricard — APPROVED** [review]

**Comment by darkobits** [comment]
@romainricard Here are steps to reproduce using the test pack:

1. Paste the test pack URL with a modified/invalid pack key into the **Signal Art URL** field.
2. Complete the rest of the form.
3. Try to submit the form. Note the form correctly reports the invalid pack key on the **Signal Art URL** field.
4. Erase this field and paste in the valid test pack URL.

> Now t hat the form has been submitted, fields should validate as soon as they are blurred.

5. Note that the field remains invalid on subsequent blurs and submits, even though the URL is valid.

Here's a video demonstrating this behavior:

**Comment by romainricard** [comment]
... ok, weird, I was almost sure that I follow your exact protocol, and it works. I retested, and sure enough, I found the bug. Sorry, and thanks for the detailed walk-through! :1st_place_medal:

**Pull request merged**
